### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by sovsep** [BenjaminETaylor/bjsfm#2]
Is it mandatory requirement to have python 3.9?
I have 3.8.8 and can't update to 3.9 currently.
When installing bjsfm I get this ERROR:
ERROR: Package 'bjsfm' requires a different Python: 3.8.8 not in '~=3.9'

Regards,
Sergej

**Comment by BenjaminETaylor** [comment]
Hi Sergej,

I wasn't able to reproduce your error, but I was able to produce the expected one.
-> tuple[complex, complex]:
TypeError: 'type' object is not subscriptable

Python => 3.9 is required because the code [uses standard names for type hints](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections).

Sorry for the inconvenience.

**Comment by BenjaminETaylor** [comment]
After thinking about this more, you can try installing an older version (0.2.4 or earlier). Those should work with Python 3.8.

Also, another option is to use the web app.
[https://www.centricengineers.com/free-software/ce-bjsfm](https://www.centricengineers.com/free-software/ce-bjsfm)

**Comment by sovsep** [comment]
Hello Benjamin,

Thanks for your answers. Yes the older versions are working just fine. I will see to update python ASAP.
The website is very usefull. Thanks for making it opensource. I have jsut registered myself.

Regards,
Sergej
